### ISSUE TITLE
Smart endpoints for readme and icon

### ISSUE THREAD

**Issue by makyo** [juju/charmstore#179]
The readme and icon should always be available under meta endpoints, as they were under the old charmstore.  The icon should return either the icon.svg file from the charm or a default icon (we have separate default icons for every category, and one for uncategorized charms), and the readme should return either the readme text or an empty string.  This will reduce our calls per details request to 1.  Low priority.

**Comment by mitechie** [comment]
I think it'd be best if it returns the icon or 404's. I don't think the back end making icon choices is best for clients. I'd expect the clients to do a manifest check before requesting an icon that doesn't exist. 

It's more work on the client end, but it makes sense from a pure api perspective. We also don't have categories or category icons in the new storefront so that will just fall by the wayside. 

I do think that having the readme as a called out endpoint or target would be great. Users have the freedom to create

```
README
readme.md
Readme.rst
```

and it's a common enough root idea in charms/bundles that having the server find/call out where that's out would be a handy api addition.

**Comment by urosj** [comment]
Implemented as $ID/icon.svg for charms, $ID/diagram.svg for bundles and $ID/readme for both.
