### ISSUE TITLE
Reject charms with no hooks

### ISSUE THREAD

**Issue by hloeung** [juju/charmstore#769]
Sometimes, people (like me) can accidentally push up a reactive charm that's not yet built. See https://jujucharms.com/u/graylog-charmers/graylog/12

Maybe the charm store should reject when there's no hooks directory or hooks directory is empty?

**Comment by paulgear** [comment]
I wonder if we could traverse all charms to see if there are any with no hooks at all.  Even the most minimal charms I've worked on always have at least one hook.

If there's no hooks directory at all, it seems likely that it's not a charm, and should be rejected.

**Comment by stub42** [comment]
A charm with no hooks could can still provide empty relation endpoints and actions affecting the base system. But now days even those **_should_** have at least an install hook that changes the workload status from unknown to active.

(so +1 for me, since uploading unbuilt charms is a surprisingly common mistake)

**Comment by fabricematrat** [comment]
https://github.com/juju/charmstore-client/issues/143
