### ISSUE TITLE
Bionic series needed

### ISSUE THREAD

**Issue by ryan-beisner** [juju/charmstore#777]
We're opening development of the Bionic (18.04) series of OpenStack Charms. Please enable the series in the charm store to enable testing and development as soon as possible. Many thanks!

**Comment by ryan-beisner** [comment]
FYI, corresponding bug to track series enablement in juju core:  https://bugs.launchpad.net/juju/+bug/1727407

**Comment by ryan-beisner** [comment]
Curious if there is an ETA for charm store Bionic support?  We do need to begin testing, and our testing requires charm store series support.  Thank you.

**Comment by mitechie** [comment]
The code for this has landed and needs to be released to production. The current thought is that the upgrade requires some downtime as other changes are in the pack of updates. The team will be talking with the IS team about the downtime and how to best schedule the update. We're shooting for Sunday (EST) so that the APAC folks can do the upgrade with as little impact on users as possible, but will know more once we have the IS call tomorrow.

**Comment by urosj** [comment]
This is now available on production.

**Comment by ryan-beisner** [comment]
:smile: Thanks, all!
